### ISSUE TITLE
如何在webpack里使用

### ISSUE THREAD

**Issue by yellowMan1988** [IFmiss/loading#1]
window.removeLoading=function(loadingName){
	var loadingName = loadingName || '';
	$('body,html').css({
		overflow:'auto',
	});

	if(loadingName == ''){
		$(".cpt-loading-mask").remove();
	}else{
		var name = loadingName || 'loadingName';
		$(".cpt-loading-mask[data-name="+name+"]").remove();		
	}
}

当引入webpack里，调用removeLoading会出错，加了window全局变量可以解决，当不知道这样解决是否为合理的方式

**Comment by AnglerDW** [comment]
![image](https://user-images.githubusercontent.com/17402583/42012237-c3171dc0-7ac9-11e8-8c3c-0089d0e7d817.png)
其实这个组件 的remove方法不应该这样写，应该挂载在loading上面，你可以先这样写，以后有时间再将这个loading用原生写并发布到npm 方便引入和使用
